version: '3'
services:
  node:
    image: "task_queues-nodeimg-${NODE_ENV}"
    container_name: "task_queues-node-${NODE_ENV}"
    restart: on-failure
    volumes:
      - ../_src:/projectFiles/_src
      - ../public:/projectFiles/public
      - ../config:/projectFiles/config
    build:
      context: .
      dockerfile: "Dockerfile-${NODE_ENV}"
    ports:
      - '3000:3000'
      - "30000:9229"
    depends_on:
      - redis
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: "task_queues-rabbitmq-${NODE_ENV}"
    restart: on-failure
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    image: redis:6.0.16
    container_name: "task_queues-redis-${NODE_ENV}"
    restart: on-failure
    ports:
      - '6379:6379'
