version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    image: redis:6.0.16
    ports:
      - '6379:6379'

  node:
    image: nodeapp
    volumes:
      - ./_src:/projectFiles/_src
      - ./public:/projectFiles/public
      - ./config:/projectFiles/config
    build:
      context: .
      dockerfile: _src/Dockerfile-dev
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - rabbitmq
