version: '3'
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    image: redis
    ports:
      - '6379:6379'

  node:
    image: nodeapp
    volumes:
      - ./public:/projectFiles/public
    env_file:
      - _src/config/credentials.env
    build:
      context: .
#      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - rabbitmq
