FROM node:18.16.0 as task_queues-nodeimg-debug

WORKDIR /projectFiles

COPY ../package.json ../tsconfig.json ../nodemon-debug.json ./

RUN npm install

ENV NODE_ENV=debug
ENV DOCKER_BUILD=true

ENTRYPOINT ["npm", "run", "start:debug"]
